### ISSUE TITLE
Evolution of mobilityDCAT-AP vs. our Controlled Vocabs

### ISSUE THREAD

**Issue by peterlubrich** [mobilityDCAT-AP/mobilityDCAT-AP#28]
So far, we have published an initial release of mobilityDCAT-AP and some own Controlled Vocabularies. Everything is in v1.0.0.
But now, we face an evolution:

- mobilityDCAT-AP will be updated as 1.0.0 -> 1.0.1
- One of our Controlled Vocab has a minor error, i.e., will be updated as 1.0.0 -> 1.0.1
- The other of our Controlled Vocabs will remain as 1.0.0.

In the end, there might be a different pace of evolution for mobilityDCAT-AP vs. our Controlled Vocabularies.
So far, the idea is that everything is independent, meaning that mobilityDCAT-AP and our Controlled Vocabularies can be updated independently.
We can keep it this way with the following benefits:
- we can do updates of our Controlled Vocabs, without "waiting" for updates of mobilityDCAT-AP, or vice versa.
- users have the freedom to deploy ANY version of mobilityDCAT-AP in combination with ANY version of our Controlled Vocabs 

However, this implies:
- We need to carefully inform about this "independent approach", and any updates of mobilityDCAT-AP AND our Controlled Vocabularies.
- We need to provide online any older versions of mobilityDCAT-AP AND our Controlled Vocabularies (so users still can upgrade step-by-step).

Any thoughts or oppositions?

**Comment by marioscrock** [comment]
I agree on having independent updates, also because at some point the mobilityDCAT-AP spec may decide to abandon a certain controlled vocab in favour of another one (e.g., a standardised vocab directly published by the EC commission). Our controlled vocabs already have a "latest" IRI that points to the latest version and versioned IRIs for previous ones.

Regarding the documentation, I think that this is already made clear by the fact that the controlled vocabs are published as a separate resource. We may add a comment in the Wiki to clarify it further. Finally, but this is not mandatory, when we update the mobilityDCAT-AP spec we may "recommend" a certain version for each controlled vocab.

**Comment by marioscrock** [comment]
We agreed during the SWG4.4 meeting 27 that mobilityDCAT-AP and the Controlled Vocabularies can be updated independently (different version numbers).
