### ISSUE TITLE
Question about the SHACL files

### ISSUE THREAD

**Issue by Joonas-M-S** [mobilityDCAT-AP/mobilityDCAT-AP#36]
The [SHACL file](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/gh-pages/releases/1.0.1/mobilitydcat-ap_shacl_shapes.ttl) has used `sh:Class` in couple places, for instancy [here](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/ba0949f296c21ced7cc5051cb955535046f29355/releases/1.0.1/mobilitydcat-ap_shacl_shapes.ttl#L364). Shouldn't all be in lowercase [sh:class](https://www.w3.org/TR/shacl/#ClassConstraintComponent)? I'm not too familiar with SHACL, but can one use both `sh:class` and `sh:pattern` as a constraint for an instance of a class as is done for `mobilitydcatap:mobilityDataStandard` parameter for `dcat:Distribution`? At least https://shacl.org/playground/ does not seem to understand it. And should [this](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/ba0949f296c21ced7cc5051cb955535046f29355/releases/1.0.1/mobilitydcat-ap_shacl_shapes.ttl#L364) be removed all together as the range of [mobilitydcatap:schema](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/ba0949f296c21ced7cc5051cb955535046f29355/releases/1.0.1/mobilitydcat-ap_shacl_shapes.ttl#L553) is `rdfs:Resource` and not `skos:Concept`?

**Comment by Daham-Mustaf** [comment]
Hi [Joonas-M-S](https://github.com/Joonas-M-S),

Thank you for your observations regarding the SHACL file (`mobilitydcat-ap_shacl_shapes.ttl`). Upon reviewing your feedback, I acknowledge the following points:

1. **Use of `sh:Class` vs `sh:class`:** I've identified inconsistencies in the SHACL file where `sh:Class` has been used instead of `sh:class`. According to the SHACL specification, all keywords should be in lowercase (`sh:class`), which I will correct accordingly.

2. **Constraint on `mobilitydcatap:mobilityDataStandard`:** You mentioned the use of both `sh:class` and `sh:pattern` as constraints for instances of a class. Using both sh:class and sh:pattern:
It is possible to use both `sh:class` and `sh:pattern` as constraints for a property. These would be interpreted as separate constraints that both need to be satisfied. The `sh:class` constraint would check the type of the value, while `sh:pattern` would check if the string representation of the value matches a given regular expression.

Based on your feedback, I will make the necessary updates to the SHACL file to address these issues.

**Comment by peterlubrich** [comment]
I see the above proposal (changing to "sh:class" in the SHACL file) has been realised in the recent [pull request #60 ](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/pull/60).
Means the updated SHACL file under mobilityDCAT-AP v1.1.0 will reflect that correction

The other discussed sub-issue is about this double-entry under property ""mobility data standard":

```
    sh:pattern "https://w3id.org/mobilitydcat-ap/mobility-data-standard" 
    sh:Class mobilitydcatap:MobilityDataStandard  
```

Jonaas has asked to delete the first line.

This sub-issue will be resolved/clarified via an upcoming issue "how to call an individual Mobility Data Standard from one Distribution" (with "cases 1 and 2"). @marioscrock Please create such issue, as requested by email.

I will close this issue #36 for now.
